### ISSUE TITLE
Passing items as arguments

### ISSUE THREAD

**Issue by prakhar1989** [fedosejev/shopping-list-react#2]
Hi 

First off, thanks for the repo. This has been tremendously useful for me to wrap my head around React. 

Just a quick question  -  if you see [this](https://github.com/fedosejev/shopping-list-react/blob/f4ff6b39e30d7019454f517aea86c36378d5a290/source/js/components/List.react.js#L39-L67) code snippet, you have passed `items` as an argument to `getListOfItemIds`, `createListItemElements` and `getTotalNumberOfListItems`. Since, `items` is already available via `this.props.items`, is this really required? Am I missing anything?

e.g.
```javascript
getListOfItemIds: function () {
    return Object.keys(this.props.items);
},
```
Thanks!

**Comment by fedosejev** [comment]
Hi Prakhar,

I am glad it's useful and thanks for you question.

The short answer is no, you're not missing anything, you could replace `items` with `this.props.items` and remove it as a parameter.

The reason why I've decided to pass `this.props.items` as an argument instead of accessing it directly in `getListOfItemIds()`, `getTotalNumberOfListItems()`, `createListItemElements()` has nothing to do with how React works, but rather how I want to decouple React-specific and non-React-specific functionality.

I could move `getListOfItemIds()` and `getTotalNumberOfListItems()` into a separate utils module, e.g.: `ListUtils.js`:

```javascript
function getListOfItemIds(items) {
  return Object.keys(items);
}

function getTotalNumberOfListItems(items) {
  var totalNumberOfItems = 0;
  var item;

  getListOfItemIds(items).forEach(function (itemId) {
    item = items[itemId];
    totalNumberOfItems = totalNumberOfItems + parseInt(item.quantity, 10);
  });

  return totalNumberOfItems;
}

module.exports = {
  getListOfItemIds: getListOfItemIds,
  getTotalNumberOfListItems: getTotalNumberOfListItems
};
```

Then reuse this module anywhere I want by requiring it and providing `items` as a parameter. The benefit of doing that is that now the source of `items` can be anything, not only `this.props.items` - this adds flexibility to my code, as it's not React-specific anymore.

Same could be done with `createListItemElements()` function, however it would take additional parameters: `ListItem` element and `handleRemoveListItem` callback function.

This is my personal design preference, and not a rule.

Hope this helps!

**Comment by prakhar1989** [comment]
Ah ok. That makes sense. Thanks again for this :+1:
